title: 陈颂光
description: 全栈工程师，承接从编译器到网站的各类软件开发与咨询，也可以聊历史哲学。
lang: zh_CN
author: 陈颂光
google_analytics: 
show_downloads: false
theme: jekyll-theme-architect
paginate: 20

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
